@baseUrl = http://localhost:4040/v1
@token = place_your_token_here

### Health Check
# Endpoint to verify the API is running
GET {{baseUrl}}/health
Accept: application/json

###

### Generate Token
# Endpoint to generate a JWT token
POST {{baseUrl}}/auth/token
Content-Type: application/json

{
    "email": "test@example.com"
}

###

### Create a Post
# Endpoint to create a new post
POST {{baseUrl}}/posts
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "My First Post",
    "content": "This is the content of my first post. It's working great!",
    "tags": ["News", "Sports"],
    "user_id": 1
}

### Get a post by id
GET {{baseUrl}}/posts/3
Accept: application/json
Authorization: Bearer {{token}}

###

### Add a comment to a post
# Endpoint to add a comment to a specific post
POST {{baseUrl}}/posts/3/comments
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "content": "This is a great post!"
}

###

### Update a post
# Endpoint to partially update a post
PATCH {{baseUrl}}/posts/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "My Updated Title",
    "content": "This content was updated via PATCH."
}

###

### Delete a post
# Endpoint to delete a specific post
DELETE {{baseUrl}}/posts/1
Authorization: Bearer {{token}}

###

### Create a User
# Endpoint to create a new user (Unprotected)
POST {{baseUrl}}/users
Content-Type: application/json

{
    "username": "testuser",
    "email": "test@example.com",
    "password": "supersecretpassword"
}

###

### Get a user by ID
# Endpoint to fetch a specific user
GET {{baseUrl}}/users/1
Accept: application/json
Authorization: Bearer {{token}}

###

### Get posts by user ID
GET {{baseUrl}}/users/1/posts?limit=2&offset=0&sort=desc
Accept: application/json
Authorization: Bearer {{token}}

###

### Search posts by user ID
# Endpoint to search user posts using filters (search term, tags, date range)
GET {{baseUrl}}/users/1/posts?limit=10&offset=0&sort=desc&search=content&tags=News,Sports&since=2023-01-01&until=2026-12-31
Accept: application/json
Authorization: Bearer {{token}}