@baseUrl = http://localhost:4040/v1

### Health Check
# Endpoint to verify the API is running
GET {{baseUrl}}/health
Accept: application/json

###

### Create a Post
# Endpoint to create a new post
POST {{baseUrl}}/posts
Content-Type: application/json

{
    "title": "My First Post",
    "content": "This is the content of my first post. It's working great!",
    "tags": ["News", "Sports"]
}

### Get a post by id
GET {{baseUrl}}/posts/3
Accept: application/json

###

### Add a comment to a post
# Endpoint to add a comment to a specific post
POST {{baseUrl}}/posts/3/comments
Content-Type: application/json

{
    "content": "This is a great post!"
}

###

### Update a post
# Endpoint to partially update a post
PATCH {{baseUrl}}/posts/1
Content-Type: application/json

{
    "title": "My Updated Title",
    "content": "This content was updated via PATCH."
}

###

### Delete a post
# Endpoint to delete a specific post
DELETE {{baseUrl}}/posts/1

###

### Create a User
# Endpoint to create a new user
POST {{baseUrl}}/users
Content-Type: application/json

{
    "username": "testuser",
    "email": "test@example.com",
    "password": "supersecretpassword"
}

###

### Get a user by ID
# Endpoint to fetch a specific user
GET {{baseUrl}}/users/1
Accept: application/json