# This file to automate environment setup and provide some
# pre-defined tools to make the app ready to run on other machines
include .env
MIGRATIONS_PATH = ./cmd/migrate/migrations
DB_ADDR = postgres://admin:adminpassword@localhost/social?sslmode=disable

.PHONY: migrate-up migrate-down run build migrate-create gen-docs

# Run the application with live-reloading
run:
	air

# Build the Go application
build:
	go build -o ./bin/main ./cmd/api

# Generate Swagger documentation
gen-docs:
	swag init -g cmd/api/main.go -d .

# Run database migrations up
migrate-up:
	migrate -path=$(MIGRATIONS_PATH) -database="$(DB_ADDR)" up

# Rollback database migrations
migrate-down:
	migrate -path=$(MIGRATIONS_PATH) -database="$(DB_ADDR)" down

# Create a new database migration
migrate-create:
	@echo "---Creating migration files---"
	migrate create -seq -ext sql -dir $(MIGRATIONS_PATH) $(filter-out $@,$(MAKECMDGOALS))

# Catch-all target to allow passing arguments to migrate-create
%:
	@: